parameters:

  app_name: "%env(APP_NAME)%"

  app_dir:
    synthetic: true

  base_dir:
    synthetic: true

  cache_dir:
    synthetic: true

  config_dir:
    synthetic: true

  log_dir: "%env(LOG_DIR)%/%app_name%"
  log_stream_name: "app"

  app_debug: "%env(APP_DEBUG)%"