imports:
  - { resource: parameters.yml }

  # presentation
  - { resource: presentation/action.yml }

  # infrastructure
  - { resource: infrastructure/logger.yml }
  - { resource: infrastructure/http.yml }
  - { resource: infrastructure/serialize.yml }
  - { resource: infrastructure/command_bus.yml }
  - { resource: infrastructure/persistence.yml }
  - { resource: infrastructure/routing.yml }

services:

  _instanceof:
    # Add the app.container tag to all services defined in this file having this type
    Symfony\Component\DependencyInjection\ContainerInterface:
      tags: [ 'app.container' ]
    # Add the app.event_dispatcher tag to all services defined in this file having this type
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
      tags: [ 'app.event_dispatcher' ]

  app.container:
    synthetic: true

  app.event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
