parameters:

  app_name:
    synthetic: true

  app_dir:
    synthetic: true

  base_dir:
    synthetic: true

  cache_dir:
    synthetic: true

  config_dir:
    synthetic: true

  log_dir: "%env(LOG_DIR)%"
  log_stream_name: "app"