imports:
  - { resource: parameters.yml }
  - { resource: services/presentation/action.yml }
  - { resource: services/infrastructure/logger.yml }
  - { resource: services/infrastructure/http.yml }
  - { resource: services/infrastructure/serialize.yml }

services:

  _instanceof:
    # Add the app.container tag to all services defined in this file having this type
    Symfony\Component\DependencyInjection\ContainerInterface:
      tags: [ 'app.container' ]

  app.container:
    synthetic: true
