imports:
  - { resource: parameters.yml }
  - { resource: services/presentation.yml }

services:

  _instanceof:
    # Add the app.container tag to all services defined in this file having this type
    Symfony\Component\DependencyInjection\ContainerInterface:
      tags: [ 'app.container' ]

    Chassis\Infrastructure\HTTP\ControllerInterface:
      tags: [ 'app.controller' ]

  app.container:
    synthetic: true

  app.controller:
    class: Chassis\Infrastructure\HTTP\Controller
    arguments: [ '@app.container' ]