imports:
  - { resource: parameters.yml }
  - { resource: services/presentation.yml }

services:

  _instanceof:
    # Add the console.command tag to all services defined in this file having this type
    Symfony\Component\DependencyInjection\ContainerInterface:
      tags: [ 'app.container' ]

  app.container:
    synthetic: true