services:

  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # this means you can fetch services directly from the container via $container->get()
    # if you don't need to do this, you can override this setting on individual services
    public: true

  Chassis\Presentation\Serializer\Serializer: ~

  Chassis\Infrastructure\Serializer\SerializerInterface: '@Chassis\Presentation\Serializer\Serializer'